const data = {
  products: [
    {
      id: 0,
      name: "Tibus' Boss Burger",
      description:
        "Big burger with 2x beef, barbecue sauce, cheese, pickle, onion & salat.",
      image: "/images/products/1.png",
      coverImage: "/images/products/cover(1).jpg",
      price: 4.8,
      discount: 20,
      size: "Big",
      weight: 500,
      prepareTime: 8,
    },
    {
      id: 1,
      name: "Leny's Crunchy Bicky",
      description:
        "Medium burger with 1x beef, triple bycky sauce, cheese, pickle, fried onion & salat.",
      image: "/images/products/3.png",
      coverImage: "/images/products/cover(7).jpg",
      price: 4.15,
      discount: 0,
      size: "Medium",
      weight: 370,
      prepareTime: 5,
    },
    {
      id: 3,
      name: "The Phil's O'sophy",
      description:
        "Medium burger with 1x beef, bacon, triple ketchup sauce, cheese, salat.",
      image: "/images/products/4.png",
      coverImage: "/images/products/cover(2).jpg",
      price: 4.0,
      discount: 0,
      size: "Medium",
      weight: 380,
      prepareTime: 6,
    },
    {
      id: 4,
      name: "Aless double steak appartment",
      description:
        "Big burger with 2x beef, bacon, andalouse sauce, onion, salat.",
      image: "/images/products/5.png",
      coverImage: "/images/products/cover(3).jpg",
      price: 4.6,
      discount: 10,
      size: "Big",
      weight: 425,
      prepareTime: 8,
    },
    {
      id: 5,
      name: "The 'Bald & bold'",
      description: "Big burger with 3x beef, pickle sauce, fried onion, salat.",
      image: "/images/products/6.png",
      coverImage: "/images/products/cover(4).jpg",
      price: 5.0,
      discount: 33,
      size: "Big",
      weight: 475,
      prepareTime: 8,
    },
    {
      id: 6,
      name: "The Rafaëlo (kid burger)",
      description:
        "Small burger with 1x beef, cheese, ketchup sauce, pickle, salat.",
      image: "/images/products/7.png",
      coverImage: "/images/products/cover(5).jpg",
      price: 2.0,
      discount: 0,
      size: "Small",
      weight: 175,
      prepareTime: 3,
    },
    {
      id: 7,
      name: "The 'Eiffel Tour Burjer'",
      description:
        "Medium burger with 2x beef, camembert cheese, tartare & wine sauce, pickle, salat.",
      image: "/images/products/8.png",
      coverImage: "/images/products/cover(6).jpg",
      price: 4.33,
      discount: 15,
      size: "Medium",
      weight: 250,
      prepareTime: 6,
    },
  ],
};

module.exports = data;
