export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const ORDER_ADD_ITEM = "ORDER_ADD_ITEM";
export const ORDER_REMOVE_ITEM = "ORDER_REMOVE_ITEM";
export const ORDER_CLEAR = "ORDER_CLEAR";
export const ORDER_CLEAR_ITEM = "ORDER_CLEAR_ITEM";
